Register common config options in ``MechDriverSetupBase``
When manually testing any ``MechDriverSetupBase`` child testing class,
the following error is shown:
  oslo_config.cfg.NoSuchOptError: no such option service_plugins in
  group [DEFAULT]

To avoid this, this patch registers the common config options during the
``MechDriverSetupBase`` setup method. The
``register_common_config_options`` will not register the options if are
alredy registered.

Related-Bug: #1968606
Change-Id: Ie324b8489e2826a9f82fc9b45ee9684a680c6a8b
(cherry picked from commit 44c03ca8e10a11f13583ba924868b4f331d3072a)